export const Actions = {
    REGISTRATION_SAVE: 'REGISTRATION_SAVE',
    REGISTRATION_SAVE_SUCCESS: 'REGISTRATION_SAVE_SUCCESS',
    REGISTRATION_SAVE_ERROR: 'REGISTRATION_SAVE_ERROR',
    GET_COUNTRIES: 'GET_COUNTRIES',
};