export const Actions = {
  GET_POSITIONS: "GET_POSITIONS",
  GET_PLAYERS_REQUEST: "GET_PLAYERS_REQUEST",
  GET_PLAYERS_SUCCESS: "GET_PLAYERS_SUCCESS",
  FILTER_PLAYERS: "FILTER_PLAYERS",
  GET_PLAYERS_ERROR: "GET_PLAYERS_ERROR"
};
